{"seeAlsoSections":[{"title":"Validation and Errors","identifiers":["doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/Validation","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ValidationError","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/CleanExit"],"generated":true}],"schemaVersion":{"major":0,"minor":1,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"title":"ExitCode","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:14ArgumentParser8ExitCodeV","modules":[{"name":"ArgumentParser"}],"navigatorTitle":[{"kind":"identifier","text":"ExitCode"}]},"abstract":[{"type":"text","text":"An error type that only includes an exit code."}],"sections":[],"identifier":{"url":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/ArgumentParser\/SQ","doc:\/\/ArgumentParser\/s5ErrorP","doc:\/\/ArgumentParser\/SH","doc:\/\/ArgumentParser\/SY","doc:\/\/ArgumentParser\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/ArgumentParser\/documentation\/ArgumentParser"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/init(_:)","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/isSuccess","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/rawValue"]},{"title":"Type Properties","identifiers":["doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/failure","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/success","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/validationFailure"]},{"title":"Default Implementations","identifiers":["doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/RawRepresentable-Implementations","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/Error-Implementations","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/Equatable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/argumentparser\/exitcode"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If youâ€™re printing custom errors messages yourself, you can throw this error"},{"type":"text","text":" "},{"type":"text","text":"to specify the exit code without adding any additional output to standard"},{"type":"text","text":" "},{"type":"text","text":"out or standard error."}]}]}],"references":{"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/success":{"role":"symbol","title":"success","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"abstract":[{"type":"text","text":"An exit code that indicates successful completion of a command."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/success","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/success"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/init(_:)":{"role":"symbol","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"ExitCode"},{"type":"text","text":" with the given code."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/init(_:)","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/init(_:)"},"doc://ArgumentParser/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ArgumentParser\/SQ"},"doc://ArgumentParser/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/ArgumentParser\/s5ErrorP"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/failure":{"role":"symbol","title":"failure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"abstract":[{"type":"text","text":"An exit code that indicates that the command failed."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/failure","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/failure"},"doc://ArgumentParser/documentation/ArgumentParser/Validation":{"role":"article","title":"Providing Custom Validation","abstract":[{"type":"text","text":"Provide helpful feedback to users when things go wrong."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/Validation","kind":"article","type":"topic","url":"\/documentation\/argumentparser\/validation"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/isSuccess":{"role":"symbol","title":"isSuccess","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuccess"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether this exit code represents the"},{"type":"text","text":" "},{"type":"text","text":"successful completion of a command."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/isSuccess","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/issuccess"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/rawrepresentable-implementations"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode":{"role":"symbol","title":"ExitCode","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"abstract":[{"type":"text","text":"An error type that only includes an exit code."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExitCode"}],"url":"\/documentation\/argumentparser\/exitcode"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/error-implementations"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/rawValue":{"role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"The exit code represented by this instance."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/rawValue","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/rawvalue"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/equatable-implementations"},"doc://ArgumentParser/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ArgumentParser\/SH"},"doc://ArgumentParser/documentation/ArgumentParser":{"role":"collection","title":"ArgumentParser","abstract":[{"type":"text","text":"Straightforward, type-safe argument parsing for Swift."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser"},"doc://ArgumentParser/documentation/ArgumentParser/CleanExit":{"role":"symbol","title":"CleanExit","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CleanExit"}],"abstract":[{"type":"text","text":"An error type that represents a clean (i.e. non-error state) exit of the"},{"type":"text","text":" "},{"type":"text","text":"utility."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/CleanExit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CleanExit"}],"url":"\/documentation\/argumentparser\/cleanexit"},"doc://ArgumentParser/documentation/ArgumentParser/ValidationError":{"role":"symbol","title":"ValidationError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}],"abstract":[{"type":"text","text":"An error type that is presented to the user as an error with parsing their"},{"type":"text","text":" "},{"type":"text","text":"command-line input."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ValidationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationError"}],"url":"\/documentation\/argumentparser\/validationerror"},"doc://ArgumentParser/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/ArgumentParser\/SY"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/init(rawvalue:)"},"doc://ArgumentParser/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ArgumentParser\/s8SendableP"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode/validationFailure":{"role":"symbol","title":"validationFailure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"abstract":[],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode\/validationFailure","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/validationfailure"}}}