{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"While "},{"type":"codeVoice","code":"ArgumentParser"},{"type":"text","text":" validates that the inputs given by your user match the requirements and types that you define in each command, there are some requirements that can’t easily be described in Swift’s type system, such as the number of elements in an array, or an expected integer value."}]},{"anchor":"Validating-Command-Line-Input","level":3,"type":"heading","text":"Validating Command-Line Input"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To validate your commands properties after parsing, implement the "},{"type":"codeVoice","code":"validate()"},{"type":"text","text":" method on any "},{"type":"codeVoice","code":"ParsableCommand"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ParsableArguments"},{"type":"text","text":" type. Throwing an error from the "},{"type":"codeVoice","code":"validate()"},{"type":"text","text":" method causes the program to print a message to standard error and exit with an error code, preventing the "},{"type":"codeVoice","code":"run()"},{"type":"text","text":" method from being called with invalid inputs."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here’s a command that prints out one or more random elements from the list you provide. Its "},{"type":"codeVoice","code":"validate()"},{"type":"text","text":" method catches three different errors that a user can make and throws a relevant error for each one."}]},{"type":"codeListing","syntax":"swift","code":["struct Select: ParsableCommand {","    @Option var count: Int = 1","    @Argument var elements: [String] = []","","    mutating func validate() throws {","        guard count >= 1 else {","            throw ValidationError(\"Please specify a 'count' of at least 1.\")","        }","","        guard !elements.isEmpty else {","            throw ValidationError(\"Please provide at least one element to choose from.\")","        }","","        guard count <= elements.count else {","            throw ValidationError(\"Please specify a 'count' less than the number of elements.\")","        }","    }","","    mutating func run() {","        print(elements.shuffled().prefix(count).joined(separator: \"\\n\"))","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you provide useful error messages, they can guide new users to success with your command-line tool!"}]},{"type":"codeListing","syntax":null,"code":["% select","Error: Please provide at least one element to choose from.","Usage: select [--count <count>] [<elements> ...]","  See 'select --help' for more information.","% select --count 2 hello","Error: Please specify a 'count' less than the number of elements.","Usage: select [--count <count>] [<elements> ...]","  See 'select --help' for more information.","% select --count 0 hello hey hi howdy","Error: Please specify a 'count' of at least 1.","Usage: select [--count <count>] [<elements> ...]","  See 'select --help' for more information.","% select --count 2 hello hey hi howdy","howdy","hey"]},{"anchor":"Handling-Post-Validation-Errors","level":2,"type":"heading","text":"Handling Post-Validation Errors"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ValidationError"},{"type":"text","text":" type is a special "},{"type":"codeVoice","code":"ArgumentParser"},{"type":"text","text":" error — a validation error’s message is always accompanied by an appropriate usage string. You can throw other errors, from either the "},{"type":"codeVoice","code":"validate()"},{"type":"text","text":" or "},{"type":"codeVoice","code":"run()"},{"type":"text","text":" method to indicate that something has gone wrong that isn’t validation-specific. Errors that conform to "},{"type":"codeVoice","code":"CustomStringConvertible"},{"type":"text","text":" or "},{"type":"codeVoice","code":"LocalizedError"},{"type":"text","text":" provide the best experience for users."}]},{"type":"codeListing","syntax":"swift","code":["struct LineCount: ParsableCommand {","    @Argument var file: String","","    mutating func run() throws {","        let contents = try String(contentsOfFile: file, encoding: .utf8)","        let lines = contents.split(separator: \"\\n\")","        print(lines.count)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The throwing "},{"type":"codeVoice","code":"String(contentsOfFile:encoding:)"},{"type":"text","text":" initializer fails when the user specifies an invalid file. "},{"type":"codeVoice","code":"ArgumentParser"},{"type":"text","text":" prints its error message to standard error and exits with an error code."}]},{"type":"codeListing","syntax":null,"code":["% line-count file1.swift","37","% line-count non-existing-file.swift","Error: The file “non-existing-file.swift” couldn’t be opened because","there is no such file."]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you print your error output yourself, you still need to throw an error from "},{"type":"codeVoice","code":"validate()"},{"type":"text","text":" or "},{"type":"codeVoice","code":"run()"},{"type":"text","text":", so that your command exits with the appropriate exit code. To avoid printing an extra error message, use the "},{"type":"codeVoice","code":"ExitCode"},{"type":"text","text":" error, which has static properties for success, failure, and validation errors, or lets you specify a specific exit code."}]},{"type":"codeListing","syntax":"swift","code":["struct RuntimeError: Error, CustomStringConvertible {","    var description: String","}","","struct Example: ParsableCommand {","    @Argument var inputFile: String","","    mutating func run() throws {","        if !ExampleCore.processFile(inputFile) {","            \/\/ ExampleCore.processFile(_:) prints its own errors","            \/\/ and returns `false` on failure.","            throw ExitCode.failure","        }","    }","}"]},{"anchor":"Handling-Transform-Errors","level":2,"type":"heading","text":"Handling Transform Errors"},{"type":"paragraph","inlineContent":[{"type":"text","text":"During argument and option parsing, you can use a closure to transform the command line strings to custom types. If this transformation fails, you can throw a "},{"type":"codeVoice","code":"ValidationError"},{"type":"text","text":"; its "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property will be displayed to the user."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In addition, you can throw your own errors. Errors that conform to "},{"type":"codeVoice","code":"CustomStringConvertible"},{"type":"text","text":" or "},{"type":"codeVoice","code":"LocalizedError"},{"type":"text","text":" provide the best experience for users."}]},{"type":"codeListing","syntax":"swift","code":["struct ExampleTransformError: Error, CustomStringConvertible {","  var description: String","}","","struct ExampleDataModel: Codable {","  let identifier: UUID","  let tokens: [String]","  let tokenCount: Int","","  static func dataModel(_ jsonString: String) throws -> ExampleDataModel  {","    guard let data = jsonString.data(using: .utf8) else { throw ValidationError(\"Badly encoded string, should be UTF-8\") }","    return try JSONDecoder().decode(ExampleDataModel.self, from: data)","  }","}","","struct Example: ParsableCommand {","  \/\/ Reads in the argument string and attempts to transform it to","  \/\/ an `ExampleDataModel` object using the `JSONDecoder`. If the","  \/\/ string is not valid JSON, `decode` will throw an error and","  \/\/ parsing will halt.","  @Argument(transform: ExampleDataModel.dataModel)","  var inputJSON: ExampleDataModel","","  \/\/ Specifiying this option will always cause the parser to exit","  \/\/ and print the custom error.","  @Option(transform: { throw ExampleTransformError(description: \"Trying to write to failOption always produces an error. Input: \\($0)\") })","  var failOption: String?","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Throwing from a transform closure benefits users by providing context and can reduce development time by pinpointing issues quickly and more precisely."}]},{"type":"codeListing","syntax":null,"code":["% example '{\"Bad JSON\"}'","Error: The value '{\"Bad JSON\"}' is invalid for '<input-json>': dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: \"The given data was not valid JSON.\", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 \"No value for key in object around character 11.\" UserInfo={NSDebugDescription=No value for key in object around character 11.})))","Usage: example <input-json> --fail-option <fail-option>","  See 'select --help' for more information."]},{"type":"paragraph","inlineContent":[{"type":"text","text":"While throwing standard library or Foundation errors adds context, custom errors provide the best experience for users and developers."}]},{"type":"codeListing","syntax":null,"code":["% example '{\"tokenCount\":0,\"tokens\":[],\"identifier\":\"F77D661C-C5B7-448E-9344-267B284F66AD\"}' --fail-option=\"Some Text Here!\"","Error: The value 'Some Text Here!' is invalid for '--fail-option <fail-option>': Trying to write to failOption always produces an error. Input: Some Text Here!","Usage: example <input-json> --fail-option <fail-option>","  See 'select --help' for more information."]}]}],"schemaVersion":{"major":0,"minor":1,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/argumentparser\/validation"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/Validation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provide helpful feedback to users when things go wrong."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Providing Custom Validation","role":"article","modules":[{"name":"ArgumentParser"}]},"hierarchy":{"paths":[["doc:\/\/ArgumentParser\/documentation\/ArgumentParser"]]},"seeAlsoSections":[{"title":"Validation and Errors","identifiers":["doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ValidationError","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/CleanExit","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode"],"generated":true}],"references":{"doc://ArgumentParser/documentation/ArgumentParser/CleanExit":{"role":"symbol","title":"CleanExit","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CleanExit"}],"abstract":[{"type":"text","text":"An error type that represents a clean (i.e. non-error state) exit of the"},{"type":"text","text":" "},{"type":"text","text":"utility."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/CleanExit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CleanExit"}],"url":"\/documentation\/argumentparser\/cleanexit"},"doc://ArgumentParser/documentation/ArgumentParser":{"role":"collection","title":"ArgumentParser","abstract":[{"type":"text","text":"Straightforward, type-safe argument parsing for Swift."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser"},"doc://ArgumentParser/documentation/ArgumentParser/ValidationError":{"role":"symbol","title":"ValidationError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}],"abstract":[{"type":"text","text":"An error type that is presented to the user as an error with parsing their"},{"type":"text","text":" "},{"type":"text","text":"command-line input."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ValidationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationError"}],"url":"\/documentation\/argumentparser\/validationerror"},"doc://ArgumentParser/documentation/ArgumentParser/ExitCode":{"role":"symbol","title":"ExitCode","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"abstract":[{"type":"text","text":"An error type that only includes an exit code."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ExitCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExitCode"}],"url":"\/documentation\/argumentparser\/exitcode"}}}